/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion;

import java.awt.Cursor;
import java.util.List;
import javax.swing.JOptionPane;
import reglas_negocio.FabricaNegocios;
import reglas_negocio.iNegocios;

/**
 *
 * @author fernando
 */
public class FrmPantallaPrincipal extends javax.swing.JFrame {
    
    List listaDatos;
    iNegocios iNegocios;

    /**
     * Creates new form FrmPantallaRegistrarHabitat
     */
    public FrmPantallaPrincipal() {
        initComponents();
        this.setLocationRelativeTo(null);
        iNegocios = FabricaNegocios.crearNegocios();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        btnMostrarRegistroHabitat = new javax.swing.JLabel();
        btnRegistroEspecies = new javax.swing.JLabel();
        btnRegistrarItinerario = new javax.swing.JLabel();
        btnRegistrarQueja = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(23, 100, 191));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Zoológico");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 6, -1, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 470, 60));

        jPanel4.setBackground(new java.awt.Color(49, 58, 73));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnMostrarRegistroHabitat.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        btnMostrarRegistroHabitat.setForeground(new java.awt.Color(255, 255, 255));
        btnMostrarRegistroHabitat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_no_image_64px.png"))); // NOI18N
        btnMostrarRegistroHabitat.setText("Registro hábitats");
        btnMostrarRegistroHabitat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMostrarRegistroHabitatMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMostrarRegistroHabitatMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnMostrarRegistroHabitatclkBotonMostrarRegistroHabitat(evt);
            }
        });
        jPanel4.add(btnMostrarRegistroHabitat, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, 50));

        btnRegistroEspecies.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        btnRegistroEspecies.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistroEspecies.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_pets_64px.png"))); // NOI18N
        btnRegistroEspecies.setText("Registro de especies");
        btnRegistroEspecies.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegistroEspeciesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnRegistroEspeciesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnRegistroEspeciesMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnRegistroEspeciesclkMostrarRegistrarEspecie(evt);
            }
        });
        jPanel4.add(btnRegistroEspecies, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, 60));

        btnRegistrarItinerario.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        btnRegistrarItinerario.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrarItinerario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_contact_details_64px.png"))); // NOI18N
        btnRegistrarItinerario.setText("Registro de itinerarios");
        btnRegistrarItinerario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnRegistrarItinerarioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnRegistrarItinerarioMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnRegistrarItinerarioMouseReleased(evt);
            }
        });
        jPanel4.add(btnRegistrarItinerario, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 197, 450, 60));

        btnRegistrarQueja.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        btnRegistrarQueja.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrarQueja.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_disclaimer_64px.png"))); // NOI18N
        btnRegistrarQueja.setText("Registrar queja");
        btnRegistrarQueja.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnRegistrarQuejaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnRegistrarQuejaMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnRegistrarQuejaMouseReleased(evt);
            }
        });
        jPanel4.add(btnRegistrarQueja, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 279, -1, 60));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 57, 470, 370));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMostrarRegistroHabitatMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMostrarRegistroHabitatMouseEntered
        setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_btnMostrarRegistroHabitatMouseEntered

    private void btnMostrarRegistroHabitatMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMostrarRegistroHabitatMouseExited
        setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_btnMostrarRegistroHabitatMouseExited

    private void btnMostrarRegistroHabitatclkBotonMostrarRegistroHabitat(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMostrarRegistroHabitatclkBotonMostrarRegistroHabitat
        try{
            listaDatos = iNegocios.recuperarDatosFormHabitat();
            FrmPantallaRegistrarHabitat frmPantallaRegistrarHabitat = FrmPantallaRegistrarHabitat.getInstance(this);
            frmPantallaRegistrarHabitat.despliegaInformacion(listaDatos);
        }catch(Exception e){
            muestraMsjError(e.getMessage());
        }
    }//GEN-LAST:event_btnMostrarRegistroHabitatclkBotonMostrarRegistroHabitat

    private void btnRegistroEspeciesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistroEspeciesMouseEntered
        setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_btnRegistroEspeciesMouseEntered

    private void btnRegistroEspeciesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistroEspeciesMouseExited
        setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_btnRegistroEspeciesMouseExited

    private void btnRegistroEspeciesclkMostrarRegistrarEspecie(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistroEspeciesclkMostrarRegistrarEspecie
        try{
            listaDatos = iNegocios.recuperarDatosFormEspecie();
            FrmPantallaRegistroEspecie frmPantallaRegistroEspecie = FrmPantallaRegistroEspecie.getInstance(this);
            frmPantallaRegistroEspecie.despliegaInformacion(listaDatos);
        }catch(Exception e){
            muestraMsjError(e.getMessage());
        }
    }//GEN-LAST:event_btnRegistroEspeciesclkMostrarRegistrarEspecie

    private void btnRegistrarItinerarioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistrarItinerarioMouseEntered
        setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_btnRegistrarItinerarioMouseEntered

    private void btnRegistrarItinerarioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistrarItinerarioMouseExited
        setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_btnRegistrarItinerarioMouseExited

    private void btnRegistrarItinerarioMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistrarItinerarioMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegistrarItinerarioMouseReleased

    private void btnRegistrarQuejaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistrarQuejaMouseEntered
        setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_btnRegistrarQuejaMouseEntered

    private void btnRegistrarQuejaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistrarQuejaMouseExited
        setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_btnRegistrarQuejaMouseExited

    private void btnRegistrarQuejaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistrarQuejaMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegistrarQuejaMouseReleased

    private void btnRegistroEspeciesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistroEspeciesMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegistroEspeciesMouseClicked

    
    public void muestraMsjError(String mensaje){
        JOptionPane.showMessageDialog(this, mensaje, "Error",JOptionPane.ERROR_MESSAGE);
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPantallaPrincipal().setVisible(true);
            }
        });
    }
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnMostrarRegistroHabitat;
    private javax.swing.JLabel btnRegistrarItinerario;
    private javax.swing.JLabel btnRegistrarQueja;
    private javax.swing.JLabel btnRegistroEspecies;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables
}
