/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion;

import exceptions.BusinessException;
import exceptions.DAOException;
import java.awt.HeadlessException;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import objetonegocio.Especie;
import objetonegocio.Habitat;
import reglas_negocio.FabricaNegocios;
import reglas_negocio.iNegocios;

/**
 *
 * @author fernando
 */
public class FrmPantallaRegistroEspecie extends javax.swing.JDialog {

    private static FrmPantallaRegistroEspecie instancia;
    private static Especie especie;
    private iNegocios iNegocios = FabricaNegocios.crearNegocios();
    private DefaultListModel mdlDisponibles;
    private DefaultListModel mdlSeleccionados = new DefaultListModel();

    /**
     * Creates new form FrmPantallaRegistroEspecie
     */
    private FrmPantallaRegistroEspecie(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        
        this.txtADescripcion.setEnabled(false);
        this.txtNombreCientifico.setEnabled(false);
        this.txtNumAnimales.setEnabled(false);
        //this.cmbCuidador.setEnabled(false);
        this.cmbHabitat.setEnabled(false);
        this.btnEditarAnimal.setEnabled(false);
        this.btnRegistrarActualizar.setEnabled(false);
 
        
    }

    public static FrmPantallaRegistroEspecie getInstance(java.awt.Frame parent) {
        if (instancia == null) {
            instancia = new FrmPantallaRegistroEspecie(parent, true);
            especie = new Especie();
        }
        
        return instancia;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNumAnimales = new javax.swing.JTextField();
        btnEditarAnimal = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtADescripcion = new javax.swing.JTextArea();
        cmbHabitat = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        txtNombreNormal = new javax.swing.JTextField();
        txtNombreCientifico = new javax.swing.JTextField();
        btnRegistrarActualizar = new javax.swing.JButton();
        btnVerificarExistencia = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(23, 100, 191));
        jPanel2.setPreferredSize(new java.awt.Dimension(481, 75));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Registro / Actualización de especies");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1180, -1));

        jPanel3.setBackground(new java.awt.Color(49, 58, 73));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nombre normal");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        txtNumAnimales.setBackground(new java.awt.Color(204, 204, 204));
        txtNumAnimales.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jPanel3.add(txtNumAnimales, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 130, 190, -1));

        btnEditarAnimal.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnEditarAnimal.setForeground(new java.awt.Color(255, 255, 255));
        btnEditarAnimal.setText("Editar Animales");
        btnEditarAnimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarAnimalclkBotonVerificarExistencia(evt);
            }
        });
        jPanel3.add(btnEditarAnimal, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 460, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nombre cientifico");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Num de animales");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Descripción");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        jScrollPane1.setBackground(new java.awt.Color(204, 204, 204));

        txtADescripcion.setBackground(new java.awt.Color(204, 204, 204));
        txtADescripcion.setColumns(20);
        txtADescripcion.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txtADescripcion.setForeground(new java.awt.Color(255, 255, 255));
        txtADescripcion.setRows(5);
        txtADescripcion.setEnabled(false);
        jScrollPane1.setViewportView(txtADescripcion);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 540, -1));

        cmbHabitat.setBackground(new java.awt.Color(204, 204, 204));
        cmbHabitat.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        cmbHabitat.setForeground(new java.awt.Color(255, 255, 255));
        cmbHabitat.setEnabled(false);
        jPanel3.add(cmbHabitat, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 400, 200, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Habitat");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, -1, -1));

        txtNombreNormal.setBackground(new java.awt.Color(204, 204, 204));
        txtNombreNormal.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jPanel3.add(txtNombreNormal, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 30, 190, -1));

        txtNombreCientifico.setBackground(new java.awt.Color(204, 204, 204));
        txtNombreCientifico.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jPanel3.add(txtNombreCientifico, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 80, 190, -1));

        btnRegistrarActualizar.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnRegistrarActualizar.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrarActualizar.setText("Registrar/Actualizar");
        btnRegistrarActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActualizarclkBotonVerificarExistencia(evt);
            }
        });
        jPanel3.add(btnRegistrarActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 460, -1, -1));

        btnVerificarExistencia.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnVerificarExistencia.setForeground(new java.awt.Color(255, 255, 255));
        btnVerificarExistencia.setText("Verificar");
        btnVerificarExistencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerificarExistenciaclkBotonVerificarExistencia(evt);
            }
        });
        jPanel3.add(btnVerificarExistencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 30, -1, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 630, 530));

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setText("Cuidadores disponibles");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable2);

        jLabel8.setBackground(new java.awt.Color(0, 0, 0));
        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel8.setText("Cuidadores seleccionados");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jLabel5))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jLabel8))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane2)
                            .addComponent(jScrollPane3))))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addGap(51, 51, 51)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(62, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 70, 550, 540));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Codigo inutil
    private void btnEditarAnimalclkBotonVerificarExistencia(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarAnimalclkBotonVerificarExistencia
        // TODO add your handling code here:

        try {
            Especie especiee = verificaExistencia();
            if (especiee != null) {
                llenaCamposInfo(especiee);
                throw new BusinessException("La especie ya existe");
            } else {
                activaCampos();
            }

        } catch (DAOException ex) {
            muestraMsjError(ex.getMessage(), JOptionPane.ERROR_MESSAGE);
        } catch (BusinessException ex) {
            muestraMsjError(ex.getMessage(), JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnEditarAnimalclkBotonVerificarExistencia

    private void btnRegistrarActualizarclkBotonVerificarExistencia(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActualizarclkBotonVerificarExistencia
   
        try{
            Especie especiee = new Especie();
            especiee.setNombreNormal(this.txtNombreNormal.getText());
            especiee.setNombreCientifico(this.txtNombreCientifico.getText());
            especiee.setDescripcion(this.txtADescripcion.getText());
            especiee.setHabitat( ((Habitat) this.cmbHabitat.getSelectedItem()) );
            if(exist)
                iNegocios.guadarEspecie(especiee);
            else
                iNegocios.guadarEspecie(especiee);
            JOptionPane.showMessageDialog(this, especiee,"Creado exitosamente", JOptionPane.INFORMATION_MESSAGE);
        }catch(DAOException | HeadlessException e){
            muestraMsjError(e.getMessage(), JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnRegistrarActualizarclkBotonVerificarExistencia
    
    //Codigo para verificar existencia
    private void btnVerificarExistenciaclkBotonVerificarExistencia(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerificarExistenciaclkBotonVerificarExistencia
        try {
            Especie especie = verificaExistencia();
            if (especie != null) {
                this.exist = true;
                llenaCamposInfo(especie);
                throw new BusinessException("La especie ya existe");
            }

        } catch (DAOException ex) {
            System.out.println("pito");
            activaCampos();
            muestraMsjError(ex.getMessage(), JOptionPane.ERROR_MESSAGE);
        } catch (BusinessException ex) {
            muestraMsjError(ex.getMessage(), JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnVerificarExistenciaclkBotonVerificarExistencia

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        this.instancia = null;
    }//GEN-LAST:event_formWindowClosed

    public void activaCampos(){
        this.txtADescripcion.setEnabled(true);
        this.txtNombreCientifico.setEnabled(true);
        this.txtNumAnimales.setEnabled(true);
        //this.cmbCuidador.setEnabled(true);
        this.cmbHabitat.setEnabled(true);
        this.btnEditarAnimal.setEnabled(true);
        this.btnRegistrarActualizar.setEnabled(true);
    }

    public Especie getEspecie() {
        return especie;
    }

    public void setEspecie(Especie especie) {
        FrmPantallaRegistroEspecie.especie = especie;
    }
    
    public void actualizarNumAnimales(int num){
        txtNumAnimales.setText(String.valueOf(num));
    }
    
    
    
    public void muestraMsjError(String mensaje, int mode) {
        JOptionPane.showMessageDialog(this, mensaje, "Error", mode);
    }

    public void llenaCamposInfo(Especie especie) {
         this.txtADescripcion.setText(especie.getDescripcion());
         this.txtNombreCientifico.setText(especie.getNombreCientifico());
         this.txtNombreNormal.setText(especie.getNombreNormal());
         /*
         for (int i = 0; i < cmbCuidador.getItemCount(); i++) {
            if(cmbCuidador.getItemAt(i).getNombre().equals(especie.getListaCuidadoresEspecie().get(i).getCuidador().getNombre())){
                cmbCuidador.setSelectedIndex(i);
            }
        }
         for (int i = 0; i < cmbHabitat.getItemCount(); i++) {
            if(cmbHabitat.getItemAt(i).getNombre().equals(especie.getHabitat().getNombre())){
                cmbHabitat.setSelectedIndex(i);
            }
        }
*/
    }

    public Especie verificaExistencia() throws DAOException, BusinessException {

        return iNegocios.buscarEspecie(txtNombreNormal.getText());
    }

    public void despliegaInformacion(List<List> datos) throws Exception {
        if (datos.isEmpty()) {
            throw new BusinessException("La lista de datos esta vacia");
        }

        for (int i = 0; i < datos.size(); i++) {
            if (datos.get(i).get(0).getClass() == Habitat.class) {
                datos.get(i).forEach(habitat -> {
                    this.cmbHabitat.addItem((Habitat) habitat);
                });
            }
            /*
            if (datos.get(i).get(0).getClass() == Cuidador.class) {
                for (Object cuidador : (((List) datos.get(i)))) {
                    this.cmbCuidador.addItem((Cuidador) cuidador);
                }
            }
*/
        }
        this.setVisible(true);
        this.setLocationRelativeTo(null);

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditarAnimal;
    private javax.swing.JButton btnRegistrarActualizar;
    private javax.swing.JButton btnVerificarExistencia;
    private javax.swing.JComboBox<Habitat> cmbHabitat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextArea txtADescripcion;
    private javax.swing.JTextField txtNombreCientifico;
    private javax.swing.JTextField txtNombreNormal;
    private javax.swing.JTextField txtNumAnimales;
    // End of variables declaration//GEN-END:variables
    private boolean exist = false;
    
}
